package com.urlshortener.service;

import com.urlshortener.dto.response.UrlResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.util.Optional;

/**
 * Cache-aside layer for the redirect hot path (Phase 3).
 *
 * Pattern: on a redirect request, check Redis first; on miss, fall through to Postgres,
 * then populate the cache for next time. On any owner-initiated mutation (update,
 * disable, delete), explicitly evict the key rather than waiting for TTL expiry —
 * this keeps "edit my link" and "disable my link" feeling instant to the owner while
 * still bounding worst-case staleness via TTL for any evictions we might miss
 * (e.g. a deploy rolling through, or a direct DB intervention).
 *
 * Negative caching: a short-TTL "this code doesn't exist" marker is cached on 404s.
 * This is what protects Postgres from the herd of repeated lookups generated by bots
 * brute-forcing random short codes (URL enumeration / brute-force alias discovery) —
 * those requests now get absorbed entirely by Redis instead of each one hitting the DB.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class CacheService {

    private static final String URL_KEY_PREFIX = "url:";
    private static final String NEGATIVE_MARKER = "__NOT_FOUND__";

    private final RedisTemplate<String, Object> redisTemplate;

    public Optional<UrlResponse> get(String cacheKey) {
        try {
            Object value = redisTemplate.opsForValue().get(URL_KEY_PREFIX + cacheKey);
            if (value == null) {
                return Optional.empty();
            }
            if (NEGATIVE_MARKER.equals(value)) {
                return Optional.of(NEGATIVE_SENTINEL);
            }
            return Optional.of((UrlResponse) value);
        } catch (Exception e) {
            // Cache failures must never take down the redirect path — fall through to DB.
            log.error("Redis GET failed for key={}, falling back to database.", cacheKey, e);
            return Optional.empty();
        }
    }

    public void put(String cacheKey, UrlResponse value, Duration ttl) {
        try {
            redisTemplate.opsForValue().set(URL_KEY_PREFIX + cacheKey, value, ttl);
        } catch (Exception e) {
            log.error("Redis SET failed for key={} — continuing without caching this entry.", cacheKey, e);
        }
    }

    public void cacheNegative(String cacheKey, Duration ttl) {
        try {
            redisTemplate.opsForValue().set(URL_KEY_PREFIX + cacheKey, NEGATIVE_MARKER, ttl);
        } catch (Exception e) {
            log.error("Redis negative-cache SET failed for key={}", cacheKey, e);
        }
    }

    public void evict(String cacheKey) {
        try {
            redisTemplate.delete(URL_KEY_PREFIX + cacheKey);
        } catch (Exception e) {
            // Worst case here is serving a stale cached entry until TTL expiry — logged
            // loudly, but not fatal, since TTL bounds the staleness window.
            log.error("Redis eviction failed for key={} — entry will remain cached until its TTL expires.", cacheKey, e);
        }
    }

    public boolean isNegative(Optional<UrlResponse> cached) {
        return cached.isPresent() && cached.get() == NEGATIVE_SENTINEL;
    }

    /** Sentinel object (identity-compared) distinguishing "cached miss" from "cached hit". */
    private static final UrlResponse NEGATIVE_SENTINEL =
            new UrlResponse(null, null, null, null, null, null, false, false, null, null, 0L, null, null);
}
